apiVersion: v1
kind: Pod
metadata:
  name: example4-invalid-one
  labels:
    name: example4-invalid-one
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  - name: invalid
    image: this-is-not-working
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
