apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1-nginx
spec:
  selector:
    matchLabels:
      app: example1-nginx
  template:
    metadata:
      labels:
        app: example1-nginx
    spec:
      containers:
      - name: example1-nginx
        image: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
