kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pod-running-test
nodes:
- role: control-plane
  image: kindest/node:v1.27.2
  extraPortMappings:
  - containerPort: 30950
    hostPort: 30950
  - containerPort: 30951
    hostPort: 30951
  - containerPort: 30952
    hostPort: 30952
  - containerPort: 30953
    hostPort: 30953
- role: worker
  image: kindest/node:v1.27.2
